#!/usr/bin/env python

# USAGE: python myHardFilter.py <donorID> <patientID> VCFfile1 VCFfile2 ... VCFfileN

#
# Import packages
#
import sys
import re 
import matplotlib
import matplotlib.colors as col
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
print 'all imported'
INCLUDEHETRO = True

def main():
    #
    # Reference ids
    #
    donId = sys.argv[1]
    patId = sys.argv[2]
    
    infiles = sys.argv[3:]
    printVcfLines = False 
    
    variations, samples = getVariations(infiles,printVcfLines)
    samples = sorted_nicely(samples)
    piechart,csvVarCount = parseVariations(variations,samples)
    makeGraphics(samples,piechart,csvVarCount)

def sorted_nicely( l ): 
    """ Sort the given iterable in the way that humans expect.""" 
    convert = lambda text: int(text) if text.isdigit() else text 
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(l, key = alphanum_key)

def getVariations(infiles,printVcfLines):
    #
    # READ ALL VARIATIONS
    #
    variations = {} #STORES ALL THA VARIATIONS
    novelVarCount = 0 # IF NOT A DBSNPID THEN ITS NOVEL COUNT THEM
    
    for infilename in infiles:
        with open(infilename) as infile:
            for line in infile:
                
                variation = {} #EACH NEW LINE IS A VARIATION
                
                if line[0] == "#": #THIS LINE IS HEADER
                    if line[1] == 'C': #THIS LINE IS HEADER WITH SAMPLE INFO
                        line = line.rstrip().split('\t')
                        #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sampleID1 ... sampleIDn
                        samples = [line[i] for i in range(9,len(line))]
                    continue
                
                line = line.rstrip().split('\t') # SPLIT THE LINE TO COLUMNS AND SAVE THE INFO DP GT GQ PL AD FOR EACH SAMPLE
                for i in range(len(line)):
                    if i == 0:
                        chromosome = line[i]
                        variation['crom'] = chromosome
                    elif i == 1:
                        position = line[i]
                        variation['pos'] = position
                    elif i == 2:
                        rsID = line[i]
                        if rsID == '.': novelVarCount+=1;rsID = 'novel#'+str(novelVarCount)
                    elif i == 3: refBase = line[i]
                    elif i == 4: altBase = line[i]
                    elif i == 5: varQual = line[i]
                    elif i == 6: passFilter = line[i]
                    elif i == 7: info = line[i]
                    elif i == 8: perSampleFormat = line[i]
                    elif i >= 9:
                        sampleInfo = line[i]
                        sampleId = samples[i-9]
                        if sampleInfo != "./.":
                            try: GT,AD,DP,GQ,PL,SB = sampleInfo.split(':') #GT:AD:DP:GQ:PL:SB
                            except:
                                #sys.stderr.write( 'ERROR variant format is not GT:AD:DP:GQ:PL: ')
                                #sys.stderr.write( '\t'.join(line) +'\n')
                                continue #SKIP THIS VARIANT
                            if DP == '.': DP = 0
                            variation[sampleId] = {'DP':DP,'GT':GT,'GQ':GQ,'PL':PL,'AD':AD,'SB':SB} #SAVE SAMPLE INFO
                            #try:
                            #    if sampleId == patId and int(DP) >= 10: print '\t'.join(line)
                            #except:
                            #    print 'ERRORSCHMERROR: ',
                            #    print  '\t'.join(line)
                            #    sys.exit()    
                if len(refBase) != len(altBase): continue
                if variation and passFilter and passFilter == 'PASS':# or variation: #SAVE VARIATION YO TABLE
                    variations[rsID] = variation
                    if printVcfLines: sys.stderr.write(  '\t'.join(line) +'\n')
    return variations, samples

def parseVariations(variations,samples):

    donId = sys.argv[1]
    patId = sys.argv[2]

    variationsTableTsv = open(samples[0].split('.')[0]+'.hetero='+str(INCLUDEHETRO)+'.variationsTable.tsv','w')
    variationsBySample = open(samples[0].split('.')[0]+'.hetero='+str(INCLUDEHETRO)+'.variationsBySample.tsv','w')
    topVariationsBySample = open(samples[0].split('.')[0]+'.hetero='+str(INCLUDEHETRO)+'.topVariationsBySample.tsv','w')
    varsByDP = {}
    samplesByDP = {}
    for sample in samples: varsByDP[sample] = {}; samplesByDP[sample] = []
    csv = 'SNP_ID,'+','.join([sample for sample in samples])
    piechart = {sample:{'PAT':0,'DON':0,'PAT_I':0,'DON_I':0,'TOTAL':0,'MIX':0,'SharedAllele':0} for sample in samples}
    patDonReadCutoff = 20
    patDonQualCutoff = 30
    readDepthCutoff = 10
    genotypeQualCutoff = 30
    
    #
    # create headers
    #
    variationsTableTsv.write('varID\tchrom\tpos\t')
    for sample in samples:
        variationsTableTsv.write(sample+' is\tDP\tGQ\tAD\t')
        variationsBySample.write('_\tvarID\t')
        variationsBySample.write(sample+' is\tDP\tGQ\tAD\t')
        topVariationsBySample.write('varID\t')
        topVariationsBySample.write(sample+' is\tDP\tGQ\tAD\t_\t')
    variationsTableTsv.write('\n')
    variationsBySample.write('\n')
    topVariationsBySample.write('\n')
        
    patientDonorPossibleVariants = 0
    csvVarCount = 0
    for varID, variation in variations.iteritems():
        
        patHetero = False
        donHetero = False
        
        #
        # filtration
        #
                
        #skip if we don't have genotypes for both pat and don
        if patId not in variation or donId not in variation: continue
        
        #skip if there is no diff betwen pat and don
        if variation[patId]['GT'] == variation[donId]['GT']: continue
        
        #skip if any of them are ./.
        if './.' in [variation[donId]['GT'],variation[patId]['GT']]: continue
        
        # skip if don not homo
        if variation[donId]['GT'].split('/').count(variation[donId]['GT'].split('/')[0]) < 2 and not INCLUDEHETRO: continue
        elif variation[donId]['GT'].split('/').count(variation[donId]['GT'].split('/')[0]) < 2: varID += '_DH'; donHetero=True
        
        # skip if pat not homo
        if variation[patId]['GT'].split('/').count(variation[patId]['GT'].split('/')[0]) < 2 and not INCLUDEHETRO: continue
        elif variation[patId]['GT'].split('/').count(variation[patId]['GT'].split('/')[0]) < 2: varID += '_PH'; patHetero=True
        
        # skip if pat and don are not both DP >= patDonReadCutoff
        if int(variation[patId]['DP']) < patDonReadCutoff or int(variation[donId]['DP']) < patDonReadCutoff: continue 
        
        # if pat and don are not both GQ >= genotypeQualCutoff 
        if int(variation[patId]['GQ']) < genotypeQualCutoff or int(variation[donId]['GQ']) < genotypeQualCutoff: continue 
        
        #
        # if variant pass all filters
        #
        else:
            
            if not patHetero and not donHetero:patientDonorPossibleVariants += 1
            
            #skip if only two samples have data
            if len(variation) <= 2: continue

            
            # classify based on sample called genotype and patient and donor genotypes
            whoAmI = {variation[patId]['GT']:'PAT',variation[donId]['GT']:'DON'}
            if (patHetero or donHetero) and INCLUDEHETRO:
                if patHetero and not donHetero: 
                    if   variation[donId]['GT'] == '0/0' and '1' in [variation[patId]['GT'][0],variation[patId]['GT'][-1]]: whoAmI['1/1']='PAT_I'
                    elif variation[donId]['GT'] == '1/1' and '0' in [variation[patId]['GT'][0],variation[patId]['GT'][-1]]: whoAmI['0/0']='PAT_I'
                    whoAmI[variation[donId]['GT']]='SharedAllele'
                    whoAmI[variation[patId]['GT']]='PAT_I'
                if donHetero and not patHetero:
                    if   variation[patId]['GT'] == '0/0' and '1' in [variation[donId]['GT'][0],variation[donId]['GT'][-1]]: whoAmI['1/1']='DON_I'
                    elif variation[patId]['GT'] == '1/1' and '0' in [variation[donId]['GT'][0],variation[donId]['GT'][-1]]: whoAmI['0/0']='DON_I'
                    whoAmI[variation[patId]['GT']]='SharedAllele'
                    whoAmI[variation[donId]['GT']]='DON_I'
                if patHetero and donHetero: continue
                
            #
            # initial values for each variant
            #
            csvLine = str(varID)+','
            piechartVar = {sample:{} for sample in samples}
            noneAboveCutoff = True
            variationsTableTsv.write(str(varID)+'\t'+str(variation['crom'])+'\t'+str(variation['pos'])+'\t')
            
            # go through samples
            for sample in samples:
    
                # check that there is any data for the variation in the sample
                if sample not in variation:
                    variationsTableTsv.write('-\t0\t0\t-\t');
                    csvLine += '0,'
                    continue
    
                # add sample to the csv line
                try:
                    if int(variation[sample]['DP']) >= readDepthCutoff and int(variation[sample]['GQ']) >= genotypeQualCutoff:
                        if sample != patId and sample != donId: noneAboveCutoff = False
                        try:
                            if   whoAmI[variation[sample]['GT']] == 'PAT': value = 2; piechartVar[sample]['PAT'] = True
                            elif whoAmI[variation[sample]['GT']] == 'DON': value = 3; piechartVar[sample]['DON'] = True
                            elif whoAmI[variation[sample]['GT']] == 'PAT_I': value = 4; piechartVar[sample]['PAT_I'] = True
                            elif whoAmI[variation[sample]['GT']] == 'DON_I': value = 5; piechartVar[sample]['DON_I'] = True
                            elif whoAmI[variation[sample]['GT']] == 'SharedAllele': value = 6; piechartVar[sample]['SharedAllele'] = True
                        except KeyError: value = 1; piechartVar[sample]['MIX'] = True #'Mix\t'
                        csvLine += str(value)+','
                    else: csvLine += '0,'
                except KeyError: csvLine += '?,'; print 'WARNING DP or GQ missing from dictionary'
                
                # add sample to variationsTableTsv
                try:             variationsTableTsv.write(whoAmI[variation[sample]['GT']]+'\t')
                except KeyError: variationsTableTsv.write('Mix\t')
                try:             variationsTableTsv.write(str(variation[sample]['DP'])+'\t')
                except KeyError: variationsTableTsv.write('?\t')
                try:             variationsTableTsv.write(str(variation[sample]['GQ'])+'\t')
                except KeyError: variationsTableTsv.write('?\t')
                try:             variationsTableTsv.write(str(variation[sample]['AD']).replace(',','|')+'\t')
                except KeyError: variationsTableTsv.write('?\t')
            
            # if at least one sample is above the deifned cutoffs
            if not noneAboveCutoff:
                csv += '\n'+csvLine[:-1]
                csvVarCount+=1
                for sample, classifications in piechartVar.iteritems():
                    assert len(classifications) <= 1,'Error there can be only one genotype per var per sample\n'
                    for classification in classifications:
                        piechart[sample][classification] += 1
                        piechart[sample]['TOTAL'] += 1

            variationsTableTsv.write('\n')
    
            for sample in samples:
                outputStr = ''
                outputStr += '\t'+str(varID)+'\t'
                if sample not in variation:
                    outputStr += '-\t0\t0\t-\t';
                    DP = 0
                    variationsBySample.write(outputStr)
                    try: varsByDP[sample][DP].append(outputStr)
                    except KeyError: varsByDP[sample][DP] = [outputStr]
                    continue
                try:                        outputStr += whoAmI[variation[sample]['GT']]+'\t'
                except KeyError:            outputStr += 'Mix\t'
                try:
                    outputStr += str(variation[sample]['DP'])+'\t'
                    DP = int(variation[sample]['DP'])
                except KeyError:            outputStr += '?\t'
                try:                        outputStr += str(variation[sample]['GQ'])+'\t'
                except KeyError:            outputStr += '?\t'
                try:                        outputStr += str(variation[sample]['AD']).replace(',','|')+'\t'
                except KeyError:            outputStr += '?\t'
                try: varsByDP[sample][DP].append(outputStr)
                except KeyError: varsByDP[sample][DP] = [outputStr]
                variationsBySample.write(outputStr)
            variationsBySample.write('\n')
    
    for sample in samples:
        readDepths = varsByDP[sample].keys()
        readDepths.sort()
        readDepths = readDepths[::-1]
        for readDepth in readDepths: samplesByDP[sample] += varsByDP[sample][readDepth]
    if [len(tmpList) for tmpList in samplesByDP.values()].count(len(samplesByDP[samples[0]])) != len(samplesByDP): print 'NOOOOOOOO!!!!'; sys.exit(1)
    else:
        for row in range(len(samplesByDP[samples[0]])): topVariationsBySample.write(''.join([samplesByDP[sample][row] for sample in samples])[1:]+'\n')
    
    tempfile = open(samples[0].split('.')[0]+'.hetero='+str(INCLUDEHETRO)+'.variationsTable.csv','w')
    tempfile.write(csv)
    tempfile.close()
    
    topVariationsBySample.close()
    variationsTableTsv.close()
    variationsBySample.close()

    print 'There are ',patientDonorPossibleVariants, ' variations where patient and donor are differing homozygous and over cutoff values.'
    
    return piechart,csvVarCount

def makeGraphics(samples,piechart,csvVarCount):

    donId = sys.argv[1]
    patId = sys.argv[2]

    patlable = 'Patient'
    donlable = 'Donor'
    mixlable = 'Mixed'
    patcolor = '#1975FF'
    paticolor = '#8CBAFF'
    doncolor = '#FF3399'
    donicolor = '#FF99CC'
    mixcolor = '#CC9900'
    SharedAllelecolor = '#8B8B8B'
    tmpdict = {patId:patId.split('.')[0]+patlable,donId:donId.split('.')[0]+donlable}
    labels = [sample if (sample != donId and sample != patId) else tmpdict[sample] for sample in samples]

    ## Make heat map
    print 'making heatmap'
    
    print 'reading csv data'
    data = pd.read_csv(samples[0].split('.')[0]+'.hetero='+str(INCLUDEHETRO)+'.variationsTable.csv', index_col=0)
    data = data.transpose()
    print 'done'
    
    print 'plotting'
    # define individual colors as hex values
    cpool2 = ['#D0D0D0',mixcolor,patcolor,doncolor]
    if INCLUDEHETRO: cpool2 = ['#D0D0D0',mixcolor,patcolor,doncolor,paticolor,donicolor,SharedAllelecolor]
    cmap3 = col.ListedColormap(cpool2, 'indexed')
    cm.register_cmap(cmap=cmap3)
    
    # Plot it out
    fig, ax = plt.subplots()
    heatmap = ax.pcolor(data, cmap=cmap3)#,shading='faceted',edgecolors='white',linewidths=1)#, alpha=0.8)
    #ax.patch.set_hatch('x')
    
    # Format
    fig = plt.gcf()
    fig.set_size_inches(csvVarCount/10,len(samples)/7.5)
    
    # turn off the frame
    ax.set_frame_on(False)
    
    # put the major ticks at the middle of each cell
    ax.set_yticks(np.arange(data.shape[0]) + 0.5, minor=False)
    ax.set_xticks(np.arange(data.shape[1]) + 0.5, minor=False)
    
    # want a more natural, table-like display
    ax.invert_yaxis()
    ax.xaxis.tick_top()
    
    # note I could have used nba_sort.columns but made "labels" instead
    ax.set_xticklabels(data.columns, minor=False,fontsize=5)
    ax.set_yticklabels(labels, minor=False,fontsize=5)
    
    # rotate the
    plt.xticks(rotation=90)
    
    ax.grid(False)
    
    # Turn off all the ticks
    ax = plt.gca()
    
    for t in ax.xaxis.get_major_ticks():
        #t.label.set_fontsize(5)
        t.tick1On = False
        t.tick2On = False
    
    for t in ax.yaxis.get_major_ticks():
        #t.label.set_fontsize(5)
        t.tick1On = False
        t.tick2On = False
    
    print 'saving'
    plt.savefig(samples[0].split('.')[0]+'.hetero='+str(INCLUDEHETRO)+".heatmap.pdf",dpi=100,bbox_inches='tight')
    plt.close()
    
    print 'making pie charts'
    from matplotlib.gridspec import GridSpec
    fig = plt.figure(figsize=(len(samples)*3, 4), dpi=300)
    the_grid = GridSpec(1,len(samples))
    sampleNumber = 0
    for sample in samples:
        labels = []
        colors = []
        sizes = []
        ax = plt.subplot(the_grid[0, sampleNumber], aspect=1)
        ax.set_title(sample+'\n('+str(piechart[sample]['TOTAL'])+' variants)')
        if piechart[sample]['TOTAL']:
            patfrac = round(100*float(piechart[sample]['PAT'])/float(piechart[sample]['TOTAL']),2)
            donfrac = round(100*float(piechart[sample]['DON'])/float(piechart[sample]['TOTAL']),2)
            patifrac = round(100*float(piechart[sample]['PAT_I'])/float(piechart[sample]['TOTAL']),2)
            donifrac = round(100*float(piechart[sample]['DON_I'])/float(piechart[sample]['TOTAL']),2)
            mixfrac = round(100*float(piechart[sample]['MIX'])/float(piechart[sample]['TOTAL']),2)
            SharedAllelefrac = round(100*float(piechart[sample]['SharedAllele'])/float(piechart[sample]['TOTAL']),2)
        else:
            patfrac = 0
            donfrac = 0
            patifrac = 0
            donifrac = 0
            mixfrac = 0
            SharedAllelefrac = 0
        if piechart[sample]['PAT'] != 0:
            labels.append(patlable)
            colors.append(patcolor)
            sizes.append(patfrac)
        if piechart[sample]['DON'] != 0:
            labels.append(donlable)
            colors.append(doncolor)
            sizes.append(donfrac)
        if piechart[sample]['PAT_I'] != 0:
            labels.append(patlable)
            colors.append(paticolor)
            sizes.append(patifrac)
        if piechart[sample]['DON_I'] != 0:
            labels.append(donlable)
            colors.append(donicolor)
            sizes.append(donifrac)
        if piechart[sample]['MIX'] != 0:
            labels.append(mixlable)
            colors.append(mixcolor)
            sizes.append(mixfrac)
        if piechart[sample]['SharedAllele'] != 0:
            labels.append('SharedAllele')
            colors.append(SharedAllelecolor)
            sizes.append(SharedAllelefrac)
        plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', shadow=True, startangle=45)
        sampleNumber += 1
    
    plt.axis('equal')
    plt.savefig(samples[0].split('.')[0]+'.hetero='+str(INCLUDEHETRO)+".piechart.pdf",dpi=300,bbox_inches='tight')
    plt.close()
    #plt.show()
    
    print 'all finished'
    
if __name__ == "__main__":
    main()
